const FETCH_MALE_USER_REQUEST = 'FETCH_MALE_USER_REQUEST';
const FETCH_MALE_USER_SUCCESS = 'FETCH_MALE_USER_SUCCESS';
const FETCH_MALE_USER_FAIL = 'FETCH_MALE_USER_FAIL';

const FETCH_FEMALE_USER_REQUEST = 'FETCH_FEMALE_USER_REQUEST';
const FETCH_FEMALE_USER_SUCCESS = 'FETCH_FEMALE_USER_SUCCESS';
const FETCH_FEMALE_USER_FAIL = 'FETCH_FEMALE_USER_FAIL';


const ADD_TO_CARD = 'ADD_TO_CARD';

const DELETE_FROM_CARD = 'DELETE_FROM_CARD';


export { FETCH_MALE_USER_REQUEST, FETCH_MALE_USER_SUCCESS, FETCH_MALE_USER_FAIL, FETCH_FEMALE_USER_REQUEST, FETCH_FEMALE_USER_SUCCESS, FETCH_FEMALE_USER_FAIL, ADD_TO_CARD, DELETE_FROM_CARD };